name: Run Testcases
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  run-react-app-tests:
    runs-on: ubuntu-latest
    steps:
      - run: cd ..
      - run: cd ..
      - run: cd ..
      - run: cd client
      - run: npm install
      - run: npm test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
